#!/usr/bin/env node

/**
 * Build-time script to scan public/Icons folder and generate a manifest
 * of all available Azure architecture icons organized by category.
 * 
 * Output: src/utils/azureIconManifest.ts
 * 
 * Usage: node scripts/generateIconManifest.mjs
 */

import { promises as fs } from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

const ICONS_DIR = path.join(__dirname, '../public/Icons');
const OUTPUT_FILE = path.join(__dirname, '../src/utils/azureIconManifest.ts');

async function scanIconsDirectory() {
  const manifest = {};
  
  try {
    const categories = await fs.readdir(ICONS_DIR, { withFileTypes: true });
    
    for (const category of categories) {
      if (!category.isDirectory()) continue;
      
      const categoryName = category.name;
      const categoryPath = path.join(ICONS_DIR, categoryName);
      
      try {
        const files = await fs.readdir(categoryPath);
        const svgFiles = files
          .filter(f => f.toLowerCase().endsWith('.svg'))
          .filter(f => !f.includes('Zone.Identifier'))  // Skip Windows metadata files
          .sort();
        
        if (svgFiles.length > 0) {
          manifest[categoryName] = svgFiles;
        }
      } catch (err) {
        console.warn(`Warning: Could not read category ${categoryName}:`, err.message);
      }
    }
    
    return manifest;
  } catch (err) {
    console.error('Error scanning icons directory:', err);
    process.exit(1);
  }
}

function generateTypeScriptCode(manifest) {
  const manifestJson = JSON.stringify(manifest, null, 2);
  
  return `/**
 * Azure Architecture Icons Manifest
 * 
 * Auto-generated by scripts/generateIconManifest.mjs
 * DO NOT EDIT MANUALLY
 * 
 * This file maps Azure service categories to available icon filenames
 * in the public/Icons directory.
 * 
 * Generated: ${new Date().toISOString()}
 */

export interface IconManifest {
  [category: string]: string[];
}

export const AZURE_ICON_MANIFEST: IconManifest = ${manifestJson};

export default AZURE_ICON_MANIFEST;
`;
}

async function main() {
  console.log('Scanning Azure icon repository...');
  console.log(`Icons directory: ${ICONS_DIR}`);
  
  const manifest = await scanIconsDirectory();
  
  const categoryCount = Object.keys(manifest).length;
  const totalIcons = Object.values(manifest).reduce((sum, icons) => sum + icons.length, 0);
  
  console.log(`Found ${categoryCount} categories with ${totalIcons} icons`);
  
  const tsCode = generateTypeScriptCode(manifest);
  
  await fs.writeFile(OUTPUT_FILE, tsCode, 'utf-8');
  
  console.log(`✓ Icon manifest generated: ${OUTPUT_FILE}`);
  console.log(`\nTop categories:`);
  
  Object.entries(manifest)
    .sort((a, b) => b[1].length - a[1].length)
    .slice(0, 10)
    .forEach(([category, icons]) => {
      console.log(`  ${category}: ${icons.length} icons`);
    });
}

main().catch(err => {
  console.error('Fatal error:', err);
  process.exit(1);
});
