"""
Resilience API endpoints.

Serves resilience evaluation results and APRL recommendations via FastAPI.
Results are read from storage (data/{subscription_id}/resilience_evaluations.json)
generated by app.resilience.run
"""

from fastapi import APIRouter, HTTPException
from typing import Optional
from pydantic import BaseModel
import logging

from app.settings import get_settings
from app.resilience.aprl_integration import APRLCatalog, load_aprl_catalog
from app.storage.resilience_evaluations_store import load_resilience_evaluations
from app.config import get_resilience_evaluations_path
from app.storage.override_store import (
    load_overrides,
    save_override,
    delete_override,
    generate_check_uuid,
    get_override_for_check
)

LOGGER = logging.getLogger(__name__)

router = APIRouter(prefix="/api/resilience", tags=["resilience"])

# Global APRL catalog (loaded once at startup)
_aprl_catalog: Optional[APRLCatalog] = None


# Pydantic models for override requests
class OverrideRequest(BaseModel):
    resource_id: str
    recommendation_id: str
    new_status: str  # "pass" or "fail"
    user_identifier: str = "user"


class DeleteOverrideRequest(BaseModel):
    resilience_check_id: str  # Can also accept check_uuid for backward compatibility


def get_aprl_catalog() -> APRLCatalog:
    """Get or initialize APRL catalog."""
    global _aprl_catalog
    
    if _aprl_catalog is None:
        settings = get_settings()
        _aprl_catalog = load_aprl_catalog(settings)
    
    return _aprl_catalog


@router.get("/health")
def resilience_health():
    """Health check endpoint."""
    try:
        catalog = get_aprl_catalog()
        summary = catalog.get_summary()
        return {
            "status": "healthy",
            "aprl_loaded": True,
            "summary": summary,
        }
    except Exception as e:
        LOGGER.error(f"Resilience health check failed: {e}")
        return {
            "status": "unhealthy",
            "aprl_loaded": False,
            "error": str(e),
        }


@router.get("/rules")
def get_all_rules(
    resource_type: Optional[str] = None,
    category: Optional[str] = None,
):
    """
    Get APRL rules, optionally filtered by resource type and category.
    
    Query params:
        - resource_type: Filter by Azure resource type (e.g., 'Microsoft.Compute/virtualMachines')
        - category: Filter by resilience category (HighAvailability, DisasterRecovery, etc.)
    
    Returns:
        List of APRL recommendations matching filters
    """
    try:
        catalog = get_aprl_catalog()
        
        if resource_type:
            rules = catalog.get_recommendations_by_resource_type(resource_type, category)
        else:
            # Return all rules
            all_rules = []
            for recs in catalog.recommendations.values():
                all_rules.extend(recs)
            
            if category:
                all_rules = [r for r in all_rules if r.category == category]
            
            rules = all_rules
        
        return {
            "count": len(rules),
            "rules": [r.to_dict() for r in rules],
        }
    
    except Exception as e:
        LOGGER.error(f"Failed to get rules: {e}")
        raise HTTPException(status_code=500, detail=str(e))




@router.get("/evaluate/{subscription_id}")
def get_subscription_evaluation(subscription_id: str):
    """
    Get resilience evaluation results for a subscription.
    
    Returns:
        All resilience evaluation results for the subscription (from stored results)
    """
    # Check if evaluation results exist
    eval_path = get_resilience_evaluations_path(subscription_id)
    if not eval_path.exists():
        raise HTTPException(
            status_code=404, 
            detail=f"Resilience evaluations not found for subscription {subscription_id}. "
                   f"Run 'python -m app.resilience.run --subscription-id {subscription_id}' first."
        )
    
    try:
        results = load_resilience_evaluations(subscription_id)
        evaluations = results.get("evaluations", {})
        
        # Calculate aggregated stats from checks
        total_resources = len(evaluations)
        total_checks = 0
        total_failed_checks = 0
        total_passed_checks = 0

        for resource_eval in evaluations.values():
            checks = resource_eval.get("checks") or []
            total_checks += len(checks)
            total_failed_checks += sum(1 for c in checks if c.get("status") == "fail")
            total_passed_checks += sum(1 for c in checks if c.get("status") == "pass")
        
        return {
            "subscription_id": subscription_id,
            "summary": {
                "total_resources_evaluated": total_resources,
                "total_checks": total_checks,
                "total_failed_checks": total_failed_checks,
                "total_passed_checks": total_passed_checks,
            },
            "evaluations": evaluations,
        }
    
    except Exception as e:
        LOGGER.error(f"Failed to load evaluations for {subscription_id}: {e}")
        raise HTTPException(status_code=500, detail=str(e))


@router.get("/evaluate/{subscription_id}/resource/{resource_id}")
def get_resource_evaluation(subscription_id: str, resource_id: str):
    """
    Get resilience evaluation for a specific resource.
    
    Returns:
        Evaluation result including checks (and deprecated findings) plus scores
    """
    # Check if evaluation results exist
    eval_path = get_resilience_evaluations_path(subscription_id)
    if not eval_path.exists():
        raise HTTPException(
            status_code=404,
            detail=f"Resilience evaluations not found for subscription {subscription_id}"
        )
    
    try:
        results = load_resilience_evaluations(subscription_id)
        evaluations = results.get("evaluations", {})
        
        if resource_id not in evaluations:
            raise HTTPException(
                status_code=404,
                detail=f"No evaluation found for resource {resource_id}"
            )
        
        return evaluations[resource_id]
    
    except HTTPException:
        raise
    except Exception as e:
        LOGGER.error(f"Failed to get evaluation for {resource_id}: {e}")
        raise HTTPException(status_code=500, detail=str(e))


@router.post("/evaluate/{subscription_id}/refresh")
def refresh_subscription_evaluation(subscription_id: str):
    """
    Trigger a refresh of resilience evaluations for a subscription.
    
    Note: This endpoint does not run the evaluator directly.
    Instead, it documents that users should run:
        python -m app.resilience.run --subscription-id {subscription_id}
    
    Returns:
        Status message with instructions
    """
    return {
        "status": "manual",
        "message": f"To refresh resilience evaluations for subscription {subscription_id}, run:",
        "command": f"python -m app.resilience.run --subscription-id {subscription_id}",
        "note": "The APRL evaluator runs as a separate command-line tool, not through the API.",
    }




@router.get("/weights")
def get_weights():
    """Get resilience category and impact weights for scoring calculations."""
    try:
        settings = get_settings()
        category_weights = settings.get_category_weights()
        impact_weights = settings.get_impact_weights()
        return {
            "category_weights": category_weights,
            "impact_weights": impact_weights,
        }
    except Exception as e:
        LOGGER.error(f"Failed to get weights: {e}")
        raise HTTPException(status_code=500, detail=str(e))


@router.get("/categories")
def get_categories():
    """Get resilience categories and their weights (deprecated - use /weights instead)."""
    try:
        settings = get_settings()
        weights = settings.get_category_weights()
        return {
            "categories": weights,
        }
    except Exception as e:
        LOGGER.error(f"Failed to get categories: {e}")
        raise HTTPException(status_code=500, detail=str(e))

@router.get("/evaluate/{subscription_id}/summary")
def get_subscription_resilience_summary(subscription_id: str):
    """
    Get resilience summary for all resources (for frontend visualization).
    
    Returns per-resource pass/fail counts and pass percentage:
        {
            "/{subscription}/...resource1": {"total_checks": 10, "passed_checks": 7, "failed_checks": 3, "pass_percentage": 70},
            "/{subscription}/...resource2": {"total_checks": 5, "passed_checks": 5, "failed_checks": 0, "pass_percentage": 100},
            ...
        }
    """
    eval_path = get_resilience_evaluations_path(subscription_id)
    if not eval_path.exists():
        raise HTTPException(
            status_code=404,
            detail=f"Resilience evaluations not found for subscription {subscription_id}. "
                   f"Run evaluations first."
        )
    
    try:
        results = load_resilience_evaluations(subscription_id)
        evaluations = results.get("evaluations", {})
        
        summary = {}
        for resource_id, evaluation in evaluations.items():
            total = evaluation.get("total_checks", 0)
            passed = evaluation.get("passed_checks", 0)
            failed = evaluation.get("failed_checks", 0)
            pass_percentage = round((passed / total * 100) if total > 0 else 0, 1)
            
            summary[resource_id] = {
                "total_checks": total,
                "passed_checks": passed,
                "failed_checks": failed,
                "pass_percentage": pass_percentage,
            }
        
        return summary
    
    except Exception as e:
        LOGGER.error(f"Failed to get resilience summary for {subscription_id}: {e}")
        raise HTTPException(status_code=500, detail=str(e))


@router.get("/{subscription_id}/overrides")
def get_overrides(subscription_id: str):
    """
    Get all user overrides for a subscription.
    
    Returns:
        Dictionary mapping check_uuid -> override data
    """
    try:
        overrides = load_overrides(subscription_id)
        return {
            "subscription_id": subscription_id,
            "overrides": overrides,
            "count": len(overrides)
        }
    except Exception as e:
        LOGGER.error(f"Failed to load overrides for {subscription_id}: {e}")
        raise HTTPException(status_code=500, detail=str(e))


@router.post("/{subscription_id}/overrides")
def create_override(subscription_id: str, request: OverrideRequest):
    """
    Create or update a user override for a specific check.
    
    Body:
        - resource_id: Azure resource ID
        - recommendation_id: APRL recommendation GUID
        - new_status: "pass" or "fail"
        - user_identifier: Optional user identifier (default: "user")
    
    Returns:
        The created/updated override including check_uuid
    """
    if request.new_status not in ["pass", "fail"]:
        raise HTTPException(
            status_code=400,
            detail="new_status must be either 'pass' or 'fail'"
        )
    
    try:
        result = save_override(
            subscription_id=subscription_id,
            resource_id=request.resource_id,
            recommendation_id=request.recommendation_id,
            new_status=request.new_status,
            user_identifier=request.user_identifier
        )
        return result
    except Exception as e:
        LOGGER.error(f"Failed to save override for {subscription_id}: {e}")
        raise HTTPException(status_code=500, detail=str(e))


@router.delete("/{subscription_id}/overrides")
def remove_override(subscription_id: str, request: DeleteOverrideRequest):
    """
    Delete a user override.
    
    Body:
        - resilience_check_id: UUID of the check override to delete
    
    Returns:
        Success status
    """
    try:
        deleted = delete_override(subscription_id, request.resilience_check_id)
        if not deleted:
            raise HTTPException(
                status_code=404,
                detail=f"Override {request.resilience_check_id} not found"
            )
        return {"deleted": True, "resilience_check_id": request.resilience_check_id}
    except HTTPException:
        raise
    except Exception as e:
        LOGGER.error(f"Failed to delete override for {subscription_id}: {e}")
        raise HTTPException(status_code=500, detail=str(e))


@router.get("/{subscription_id}/overrides/check")
def get_check_override(
    subscription_id: str,
    resource_id: str,
    recommendation_id: str
):
    """
    Get the override for a specific check if it exists.
    
    Query params:
        - resource_id: Azure resource ID
        - recommendation_id: APRL recommendation GUID
    
    Returns:
        Override data if exists, null otherwise
    """
    try:
        override = get_override_for_check(
            subscription_id=subscription_id,
            resource_id=resource_id,
            recommendation_id=recommendation_id
        )
        
        if override:
            check_uuid = generate_check_uuid(resource_id, recommendation_id)
            return {
                "check_uuid": check_uuid,
                **override
            }
        else:
            return None
    except Exception as e:
        LOGGER.error(f"Failed to get check override for {subscription_id}: {e}")
        raise HTTPException(status_code=500, detail=str(e))

