"""
API Routes for APRL recommendations.

Serves recommendations generated by the resilience module in WARA-compatible format.
The resilience module replaces the WARA CLI tool with equivalent functionality.
"""

import json
from pathlib import Path
from fastapi import APIRouter, HTTPException, Query
from typing import Optional, List

from app.config import get_subscription_dir
from app.logger import get_logger

LOGGER = get_logger(__name__)

router = APIRouter(
    prefix="/api/subscriptions",
    tags=["recommendations"]
)


@router.get("/{subscription_id}/recommendations")
async def get_all_recommendations(
    subscription_id: str,
    category: Optional[str] = None,
    impact: Optional[str] = None,
):
    """
    Get APRL recommendations for a subscription.
    
    This endpoint serves recommendations generated by the resilience module
    which replaces the WARA CLI tool.
    
    Query Parameters:
        category: Filter by category ['HighAvailability', 'DisasterRecovery', etc.]
        impact: Filter by impact ['High', 'Medium', 'Low']
    
    Returns:
        {
            "version": "1.0",
            "subscriptionId": "...",
            "recommendations": [...],
            "summary": {
                "total": int,
                "by_impact": {...},
                "by_category": {...}
            }
        }
    """
    try:
        # Load WARA-compatible recommendations
        data_path = get_subscription_dir(subscription_id)
        rec_file = data_path / "aprl_recommendations.json"
        
        if not rec_file.exists():
            raise HTTPException(
                status_code=404,
                detail=f"No recommendations found for subscription {subscription_id}. Run the resilience evaluation first."
            )
        
        with open(rec_file) as f:
            data = json.load(f)
        
        recommendations = data.get('recommendations', [])
        
        # Filter by category if provided
        if category:
            recommendations = [
                r for r in recommendations
                if r.get('category', '').lower() == category.lower()
            ]
        
        # Filter by impact if provided
        if impact:
            recommendations = [
                r for r in recommendations
                if r.get('impact', '').lower() == impact.lower()
            ]
        
        # Build summary
        by_impact = {"High": 0, "Medium": 0, "Low": 0}
        by_category = {}
        
        for rec in recommendations:
            impact_val = rec.get('impact', 'Medium')
            by_impact[impact_val] = by_impact.get(impact_val, 0) + 1
            
            category_val = rec.get('category', 'Other')
            by_category[category_val] = by_category.get(category_val, 0) + 1
        
        return {
            "version": data.get('version', '1.0'),
            "generated": data.get('generated'),
            "subscriptionId": subscription_id,
            "recommendations": recommendations,
            "summary": {
                "total": len(recommendations),
                "by_impact": by_impact,
                "by_category": by_category
            }
        }
        
    except FileNotFoundError as e:
        raise HTTPException(
            status_code=404,
            detail=f"No data found for subscription {subscription_id}: {str(e)}"
        )
    except Exception as e:
        LOGGER.error(f"Error fetching recommendations: {e}", exc_info=True)
        raise HTTPException(
            status_code=500,
            detail=f"Error fetching recommendations: {str(e)}"
        )


@router.get("/{subscription_id}/resources/{resource_id:path}/recommendations")
async def get_resource_recommendations(
    subscription_id: str,
    resource_id: str,
):
    """
    Get APRL recommendations for a specific resource.
    
    The resource_id should be the full Azure resource ID.
    
    Returns:
        {
            "resourceId": str,
            "recommendations": [...],
            "total": int
        }
    """
    try:
        # Load recommendations
        data_path = get_subscription_dir(subscription_id)
        rec_file = data_path / "aprl_recommendations.json"
        
        if not rec_file.exists():
            raise HTTPException(
                status_code=404,
                detail=f"No recommendations found for subscription {subscription_id}"
            )
        
        with open(rec_file) as f:
            data = json.load(f)
        
        # Filter by resource ID (case-insensitive comparison)
        resource_id_lower = resource_id.lower()
        matching = [
            r for r in data.get('recommendations', [])
            if r.get('id', '').lower() == resource_id_lower
        ]
        
        return {
            "resourceId": resource_id,
            "recommendations": matching,
            "total": len(matching)
        }
        
    except FileNotFoundError:
        raise HTTPException(
            status_code=404,
            detail=f"No data found for subscription {subscription_id}"
        )
    except Exception as e:
        LOGGER.error(f"Error fetching resource recommendations: {e}", exc_info=True)
        raise HTTPException(
            status_code=500,
            detail=f"Error fetching recommendations: {str(e)}"
        )


@router.get("/{subscription_id}/recommendations/by-category/{category}")
async def get_recommendations_by_category(
    subscription_id: str,
    category: str,
):
    """
    Get all recommendations in a specific category.
    
    Valid categories: HighAvailability, DisasterRecovery, MonitoringAndAlerting, 
                     Security, Scalability, etc.
    
    Returns:
        {
            "category": str,
            "recommendations": [...],
            "total": int
        }
    """
    try:
        # Load recommendations
        data_path = get_subscription_dir(subscription_id)
        rec_file = data_path / "aprl_recommendations.json"
        
        if not rec_file.exists():
            raise HTTPException(
                status_code=404,
                detail=f"No recommendations found for subscription {subscription_id}"
            )
        
        with open(rec_file) as f:
            data = json.load(f)
        
        # Filter by category (case-insensitive)
        matching = [
            r for r in data.get('recommendations', [])
            if r.get('category', '').lower() == category.lower()
        ]
        
        return {
            "category": category,
            "recommendations": matching,
            "total": len(matching)
        }
        
    except FileNotFoundError:
        raise HTTPException(
            status_code=404,
            detail=f"No data found for subscription {subscription_id}"
        )
    except Exception as e:
        LOGGER.error(f"Error fetching category recommendations: {e}", exc_info=True)
        raise HTTPException(
            status_code=500,
            detail=f"Error fetching recommendations: {str(e)}"
        )


@router.get("/{subscription_id}/recommendations/summary")
async def get_recommendations_summary(
    subscription_id: str,
):
    """
    Get summary statistics about recommendations.
    
    Returns:
        {
            "subscriptionId": str,
            "total": int,
            "by_impact": {
                "High": int,
                "Medium": int,
                "Low": int
            },
            "by_category": {
                "HighAvailability": int,
                ...
            }
        }
    """
    try:
        # Load recommendations
        data_path = get_subscription_dir(subscription_id)
        rec_file = data_path / "aprl_recommendations.json"
        
        if not rec_file.exists():
            raise HTTPException(
                status_code=404,
                detail=f"No recommendations found for subscription {subscription_id}"
            )
        
        with open(rec_file) as f:
            data = json.load(f)
        
        recommendations = data.get('recommendations', [])
        
        # Build summary
        by_impact = {"High": 0, "Medium": 0, "Low": 0}
        by_category = {}
        
        for rec in recommendations:
            # Count by impact
            impact = rec.get('impact', 'Medium')
            by_impact[impact] = by_impact.get(impact, 0) + 1
            
            # Count by category
            category = rec.get('category', 'Other')
            by_category[category] = by_category.get(category, 0) + 1
        
        return {
            "subscriptionId": subscription_id,
            "total": len(recommendations),
            "by_impact": by_impact,
            "by_category": by_category,
            "generated": data.get('generated')
        }
        
    except FileNotFoundError:
        raise HTTPException(
            status_code=404,
            detail=f"No data found for subscription {subscription_id}"
        )
    except Exception as e:
        LOGGER.error(f"Error fetching summary: {e}", exc_info=True)
        raise HTTPException(
            status_code=500,
            detail=f"Error fetching summary: {str(e)}"
        )

