"""
API Routes for APRL recommendations.

Serves recommendations generated by the resilience module in WARA-compatible format.
The resilience module replaces the WARA CLI tool with equivalent functionality.

Updated: 2026-01-15 - Added zonal resilience endpoints
"""

import json
from pathlib import Path
from fastapi import APIRouter, HTTPException, Query
from typing import Optional, List

from app.config import get_subscription_dir
from app.logger import get_logger
from app.storage._json_repo import path_exists, read_json

LOGGER = get_logger(__name__)

router = APIRouter(
    prefix="/api/subscriptions",
    tags=["recommendations"]
)


@router.get("/{subscription_id}/recommendations")
async def get_all_recommendations(
    subscription_id: str,
    category: Optional[str] = None,
    impact: Optional[str] = None,
):
    """
    Get APRL recommendations for a subscription.
    
    This endpoint serves recommendations generated by the resilience module
    which replaces the WARA CLI tool.
    
    Query Parameters:
        category: Filter by category ['HighAvailability', 'DisasterRecovery', etc.]
        impact: Filter by impact ['High', 'Medium', 'Low']
    
    Returns:
        {
            "version": "1.0",
            "subscriptionId": "...",
            "recommendations": [...],
            "summary": {
                "total": int,
                "by_impact": {...},
                "by_category": {...}
            }
        }
    """
    try:
        # Load resilience evaluations
        data_path = get_subscription_dir(subscription_id)
        eval_file = data_path / "resilience_evaluations.json"
        
        if not path_exists(eval_file):
            raise HTTPException(
                status_code=404,
                detail=f"No recommendations found for subscription {subscription_id}. Run the resilience evaluation first."
            )

        data = read_json(eval_file, default={})
        
        # Extract recommendations from evaluations (only failed checks)
        recommendations = []
        for resource_id, evaluation in data.get('evaluations', {}).items():
            for check in evaluation.get('checks', []):
                if check.get('status') == 'fail':
                    recommendations.append({
                        "recommendationId": check.get('recommendation_id', ''),
                        "description": check.get('description', ''),
                        "category": check.get('category', ''),
                        "impact": check.get('impact', ''),
                        "type": evaluation.get('resource_type', ''),
                        "id": resource_id,
                        "name": evaluation.get('resource_name', ''),
                        "resourceGroup": resource_id.split('/resourceGroups/')[1].split('/')[0] if '/resourceGroups/' in resource_id else '',
                        "potentialBenefits": check.get('potential_benefits', ''),
                        "longDescription": check.get('long_description', ''),
                        "learnMoreLink": [check.get('learn_more', {})] if check.get('learn_more') else []
                    })
        
        # Filter by category if provided
        if category:
            recommendations = [
                r for r in recommendations
                if r.get('category', '').lower() == category.lower()
            ]
        
        # Filter by impact if provided
        if impact:
            recommendations = [
                r for r in recommendations
                if r.get('impact', '').lower() == impact.lower()
            ]
        
        # Build summary
        by_impact = {"High": 0, "Medium": 0, "Low": 0}
        by_category = {}
        
        for rec in recommendations:
            impact_val = rec.get('impact', 'Medium')
            by_impact[impact_val] = by_impact.get(impact_val, 0) + 1
            
            category_val = rec.get('category', 'Other')
            by_category[category_val] = by_category.get(category_val, 0) + 1
        
        return {
            "version": data.get('version', '1.0'),
            "generated": data.get('generated'),
            "subscriptionId": subscription_id,
            "recommendations": recommendations,
            "summary": {
                "total": len(recommendations),
                "by_impact": by_impact,
                "by_category": by_category
            }
        }
        
    except FileNotFoundError as e:
        raise HTTPException(
            status_code=404,
            detail=f"No data found for subscription {subscription_id}: {str(e)}"
        )
    except Exception as e:
        LOGGER.error(f"Error fetching recommendations: {e}", exc_info=True)
        raise HTTPException(
            status_code=500,
            detail=f"Error fetching recommendations: {str(e)}"
        )


@router.get("/{subscription_id}/resources/{resource_id:path}/recommendations")
async def get_resource_recommendations(
    subscription_id: str,
    resource_id: str,
):
    """
    Get APRL recommendations for a specific resource.
    
    The resource_id should be the full Azure resource ID.
    
    Returns:
        {
            "resourceId": str,
            "recommendations": [...],
            "total": int
        }
    """
    try:
        # Load resilience evaluations
        data_path = get_subscription_dir(subscription_id)
        eval_file = data_path / "resilience_evaluations.json"
        
        if not path_exists(eval_file):
            raise HTTPException(
                status_code=404,
                detail=f"No recommendations found for subscription {subscription_id}"
            )
        
        data = read_json(eval_file, default={})
        
        # Filter by resource ID (case-insensitive comparison)
        resource_id_lower = resource_id.lower()
        matching = []
        
        for res_id, evaluation in data.get('evaluations', {}).items():
            if res_id.lower() == resource_id_lower:
                for check in evaluation.get('checks', []):
                    if check.get('status') == 'fail':
                        matching.append({
                            "recommendationId": check.get('recommendation_id', ''),
                            "description": check.get('description', ''),
                            "category": check.get('category', ''),
                            "impact": check.get('impact', ''),
                            "type": evaluation.get('resource_type', ''),
                            "id": res_id,
                            "name": evaluation.get('resource_name', ''),
                            "resourceGroup": res_id.split('/resourceGroups/')[1].split('/')[0] if '/resourceGroups/' in res_id else '',
                            "potentialBenefits": check.get('potential_benefits', ''),
                            "longDescription": check.get('long_description', ''),
                            "learnMoreLink": [check.get('learn_more', {})] if check.get('learn_more') else []
                        })
                break
        
        return {
            "resourceId": resource_id,
            "recommendations": matching,
            "total": len(matching)
        }
        
    except FileNotFoundError:
        raise HTTPException(
            status_code=404,
            detail=f"No data found for subscription {subscription_id}"
        )
    except Exception as e:
        LOGGER.error(f"Error fetching resource recommendations: {e}", exc_info=True)
        raise HTTPException(
            status_code=500,
            detail=f"Error fetching recommendations: {str(e)}"
        )


@router.get("/{subscription_id}/recommendations/by-category/{category}")
async def get_recommendations_by_category(
    subscription_id: str,
    category: str,
):
    """
    Get all recommendations in a specific category.
    
    Valid categories: HighAvailability, DisasterRecovery, MonitoringAndAlerting, 
                     Security, Scalability, etc.
    
    Returns:
        {
            "category": str,
            "recommendations": [...],
            "total": int
        }
    """
    try:
        # Load resilience evaluations
        data_path = get_subscription_dir(subscription_id)
        eval_file = data_path / "resilience_evaluations.json"
        
        if not path_exists(eval_file):
            raise HTTPException(
                status_code=404,
                detail=f"No recommendations found for subscription {subscription_id}"
            )
        
        data = read_json(eval_file, default={})
        
        # Filter by category (case-insensitive)
        matching = []
        for resource_id, evaluation in data.get('evaluations', {}).items():
            for check in evaluation.get('checks', []):
                if check.get('status') == 'fail' and check.get('category', '').lower() == category.lower():
                    matching.append({
                        "recommendationId": check.get('recommendation_id', ''),
                        "description": check.get('description', ''),
                        "category": check.get('category', ''),
                        "impact": check.get('impact', ''),
                        "type": evaluation.get('resource_type', ''),
                        "id": resource_id,
                        "name": evaluation.get('resource_name', ''),
                        "resourceGroup": resource_id.split('/resourceGroups/')[1].split('/')[0] if '/resourceGroups/' in resource_id else '',
                        "potentialBenefits": check.get('potential_benefits', ''),
                        "longDescription": check.get('long_description', ''),
                        "learnMoreLink": [check.get('learn_more', {})] if check.get('learn_more') else []
                    })
        
        return {
            "category": category,
            "recommendations": matching,
            "total": len(matching)
        }
        
    except FileNotFoundError:
        raise HTTPException(
            status_code=404,
            detail=f"No data found for subscription {subscription_id}"
        )
    except Exception as e:
        LOGGER.error(f"Error fetching category recommendations: {e}", exc_info=True)
        raise HTTPException(
            status_code=500,
            detail=f"Error fetching recommendations: {str(e)}"
        )


@router.get("/{subscription_id}/recommendations/summary")
async def get_recommendations_summary(
    subscription_id: str,
):
    """
    Get summary statistics about recommendations.
    
    Returns:
        {
            "subscriptionId": str,
            "total": int,
            "by_impact": {
                "High": int,
                "Medium": int,
                "Low": int
            },
            "by_category": {
                "HighAvailability": int,
                ...
            }
        }
    """
    try:
        # Load resilience evaluations
        data_path = get_subscription_dir(subscription_id)
        eval_file = data_path / "resilience_evaluations.json"
        
        if not path_exists(eval_file):
            raise HTTPException(
                status_code=404,
                detail=f"No recommendations found for subscription {subscription_id}"
            )
        
        data = read_json(eval_file, default={})
        
        # Extract failed checks as recommendations
        recommendations = []
        for resource_id, evaluation in data.get('evaluations', {}).items():
            for check in evaluation.get('checks', []):
                if check.get('status') == 'fail':
                    recommendations.append(check)
        
        # Build summary
        by_impact = {"High": 0, "Medium": 0, "Low": 0}
        by_category = {}
        
        for rec in recommendations:
            # Count by impact
            impact = rec.get('impact', 'Medium')
            by_impact[impact] = by_impact.get(impact, 0) + 1
            
            # Count by category
            category = rec.get('category', 'Other')
            by_category[category] = by_category.get(category, 0) + 1
        
        return {
            "subscriptionId": subscription_id,
            "total": len(recommendations),
            "by_impact": by_impact,
            "by_category": by_category,
            "generated": data.get('generated')
        }
        
    except FileNotFoundError:
        raise HTTPException(
            status_code=404,
            detail=f"No data found for subscription {subscription_id}"
        )
    except Exception as e:
        LOGGER.error(f"Error fetching summary: {e}", exc_info=True)
        raise HTTPException(
            status_code=500,
            detail=f"Error fetching summary: {str(e)}"
        )


@router.get("/{subscription_id}/zonal-resilience")
async def get_zonal_resilience(subscription_id: str):
    """
    Get zonal resilience analysis for a subscription.
    
    Returns zone configuration data including:
    - Summary metrics (zone-redundant, multi-zone, single-zone counts)
    - 3-AZ compliance status
    - Per-resource zone configuration
    - Recommendations for improvement
    
    Returns:
        {
            "subscription_id": "...",
            "analysis_timestamp": "2026-01-15T10:30:00Z",
            "summary": {
                "total_resources": int,
                "zone_redundant_resources": int,
                "multi_zone_resources": int,
                "single_zone_resources": int,
                "unknown_zone_resources": int,
                "compliant_3az_resources": int,
                "overall_3az_compliant": bool,
                "zonal_resilience_score": float,
                "compliance_percentage": float
            },
            "resources": [
                {
                    "resource_id": "...",
                    "resource_name": "...",
                    "resource_type": "...",
                    "location": "...",
                    "zonal_data": {
                        "zones_used": [...],
                        "is_zone_redundant": bool,
                        "zone_count": int,
                        "meets_3az_requirement": bool,
                        "deployment_pattern": "zone_redundant|multi_zone|single_zone|unknown",
                        "recommendation": "..."
                    }
                }
            ]
        }
    """
    zonal_file = get_subscription_dir(subscription_id) / "zonal_resilience.json"
    
    if not path_exists(zonal_file):
        raise HTTPException(
            status_code=404,
            detail=f"Zonal resilience data not found for subscription {subscription_id}. "
                   f"Run resilience evaluation first."
        )
    
    try:
        data = read_json(zonal_file, default={})
        return data
    except Exception as e:
        LOGGER.error(f"Error reading zonal resilience data: {e}", exc_info=True)
        raise HTTPException(status_code=500, detail=str(e))


@router.get("/{subscription_id}/zonal-resilience/summary")
async def get_zonal_resilience_summary(subscription_id: str):
    """
    Get zonal resilience summary metrics only (without per-resource details).
    
    Lighter endpoint for dashboard cards and overview displays.
    
    Returns:
        {
            "subscription_id": "...",
            "analysis_timestamp": "...",
            "summary": { ... }
        }
    """
    zonal_file = get_subscription_dir(subscription_id) / "zonal_resilience.json"
    
    if not path_exists(zonal_file):
        raise HTTPException(
            status_code=404,
            detail=f"Zonal resilience data not found for subscription {subscription_id}"
        )
    
    try:
        data = read_json(zonal_file, default={})
        
        # Return only summary data
        return {
            "subscription_id": data.get("subscription_id"),
            "analysis_timestamp": data.get("analysis_timestamp"),
            "summary": data.get("summary", {})
        }
    except Exception as e:
        LOGGER.error(f"Error reading zonal resilience summary: {e}", exc_info=True)
        raise HTTPException(status_code=500, detail=str(e))


@router.get("/{subscription_id}/zonal-resilience/evaluations")
async def get_zonal_resilience_evaluations(subscription_id: str):
    """
    Get resilience evaluation details for zonal resilience analysis.
    
    Returns evaluation checks for each resource including failure reasons and LLM reasoning.
    Used by the frontend Zonal Resiliency component to display rationale for non-compliant resources.
    
    Returns:
        {
            "subscription_id": "...",
            "evaluations": {
                "resource_id": {
                    "resource_id": "...",
                    "resource_type": "...",
                    "resource_name": "...",
                    "checks": [
                        {
                            "recommendation_id": "...",
                            "description": "...",
                            "category": "...",
                            "status": "pass|fail",
                            "llm_reasoning": "...",
                            ...
                        }
                    ]
                }
            }
        }
    """
    from app.storage.resilience_evaluations_store import load_resilience_evaluations
    
    try:
        results = load_resilience_evaluations(subscription_id)
        evaluations = results.get("evaluations", {})
        
        return {
            "subscription_id": subscription_id,
            "evaluations": evaluations
        }
    except FileNotFoundError:
        raise HTTPException(
            status_code=404,
            detail=f"Resiliency evaluations not found for subscription {subscription_id}. "
                   f"Run resilience evaluation first."
        )
    except Exception as e:
        LOGGER.error(f"Error reading resilience evaluations for {subscription_id}: {e}", exc_info=True)
        raise HTTPException(status_code=500, detail=str(e))
